#!/usr/bin/env python3
"""Generate the ROADMAP status view from per-PRD state files (PRD-018).

The status of the work used to be a hand-edited region of ROADMAP.md — contended state two
operators would race on. Now it is a *generated view*: this reads `.orchestrator/prds/*.json` and
writes a managed sentinel block into ROADMAP.md. `--check` fails if the block is stale (a drift
guard, like `run.py --check-sync`), so the status is never hand-edited concurrently.

  roadmap_status.py render     # (re)generate the managed status block in ROADMAP.md
  roadmap_status.py --check    # exit nonzero if the block is missing or stale
"""
import json
import os
import re
import sys

BEGIN = "<!-- ORCHESTRATOR-LOOP:STATUS:BEGIN (generated by roadmap_status.py — do not hand-edit) -->"
END = "<!-- ORCHESTRATOR-LOOP:STATUS:END -->"
BLOCK_RE = re.compile(
    r"<!-- ORCHESTRATOR-LOOP:STATUS:BEGIN.*?-->.*?<!-- ORCHESTRATOR-LOOP:STATUS:END -->\n?",
    re.DOTALL)


def pdir():
    return os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()


def _num(pid):
    m = re.search(r"(\d+)", pid)
    return int(m.group(1)) if m else 0


def _states(d):
    dd = os.path.join(d, ".orchestrator", "prds")
    out = {}
    if os.path.isdir(dd):
        for f in sorted(os.listdir(dd)):
            if f.endswith(".json"):
                try:
                    o = json.load(open(os.path.join(dd, f)))
                    out[o.get("id", f[:-5])] = o.get("status")
                except Exception:
                    pass
    return out


def render_block(d):
    st = _states(d)
    shipped = sorted((p for p, s in st.items() if s == "shipped"), key=_num)
    open_ = sorted((p for p, s in st.items() if s != "shipped"), key=_num)

    def nums(lst):
        return " ".join(f"{_num(p):03d}" for p in lst) or "—"

    body = (f"- Shipped ({len(shipped)}): {nums(shipped)}\n"
            f"- Open ({len(open_)}): {nums(open_)}")
    return f"{BEGIN}\n{body}\n{END}\n"


def render(d):
    path = os.path.join(d, "ROADMAP.md")
    text = open(path).read() if os.path.exists(path) else "# Roadmap\n\n## Status\n"
    block = render_block(d)
    if BLOCK_RE.search(text):
        new = BLOCK_RE.sub(block, text)
    elif "## Status\n" in text:
        new = text.replace("## Status\n", f"## Status\n\n{block}", 1)
    else:
        new = text.rstrip("\n") + f"\n\n## Status\n\n{block}"
    with open(path, "w") as f:
        f.write(new)
    print("roadmap status: regenerated ✓")
    return 0


def check(d):
    path = os.path.join(d, "ROADMAP.md")
    text = open(path).read() if os.path.exists(path) else ""
    m = BLOCK_RE.search(text)
    if not m:
        sys.stderr.write("roadmap status: no generated block — run `roadmap_status.py render`\n")
        return 1
    if m.group(0).strip() != render_block(d).strip():
        sys.stderr.write("roadmap status: STALE — block differs from state files; run `render`\n")
        return 1
    print("roadmap status: in sync ✓")
    return 0


def main(argv):
    d = pdir()
    cmd = argv[0] if argv else "--check"
    if cmd == "render":
        return render(d)
    if cmd in ("--check", "check"):
        return check(d)
    print(f"usage: roadmap_status.py [render|--check] (got {cmd!r})", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
